[general]
host = "0.0.0.0"
port = 80
root = "."
compression = true # enables dynamic gzip/brotli compression
compression-static = true # serves precompressed .gz or .br files when available
compression-gzip-extensions = ["css", "png", "jpg", "jpeg", "svg", "gif"] # gzip only these types
compression-brotli-extensions = ["css", "png", "jpg", "jpeg", "svg", "gif"] # brotli only these types
http-etag = true # enables ETag header
http-last-modified = true # enables Last-Modified header
cache-control-max-age = 0 # short default cache for html and misc files
cache-control-immutable = false # disables immutable for non assets

[[headers]]
source = "**/*.{css,png,jpg,jpeg,svg,gif}" # pattern to match assets
headers = { "Cache-Control" = "public, max-age=31536000, immutable" } # replicates nginx caching header

[[headers]]
source = "**/*.html" # pattern to match html files
headers = { "Cache-Control" = "no-cache" } # ensures html is always revalidated
